#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MiUberAndroid.Resource", IsApplication=true)]

namespace MiUberAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnLogIn = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int btnNext = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int btnSendCode = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int btnSendRecoveryEmail = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int btnSignIn = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int edtBirthDay = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int edtConfirmPassword = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int edtEmail = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int edtEmaill = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int edtLastName = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int edtName = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int edtNumberPhone = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int edtPassword = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int txtNumberPhone = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int txtPasswordForgot = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int txtSignIn = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int txtThisPhone = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int txvInstructions = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ForgotPassword = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignIn = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ValidateNumberPhone = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040011
			public const int BtnSignIn = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int Email = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int EmailPlaceHolder = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Instructions = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int LogIn = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int Next = 2130968597;
			
			// aapt resource value: 0x7f040003
			public const int Password = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int PasswordForgot = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int PutConfirmPassword = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int PutLastName = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int PutName = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int PutNumberPhone = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int PutPassword = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int Send = 2130968583;
			
			// aapt resource value: 0x7f040013
			public const int SendValidationCode = 2130968595;
			
			// aapt resource value: 0x7f040006
			public const int SignIn = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int UserNumberPhone = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int ValidationCode = 2130968596;
			
			// aapt resource value: 0x7f04000d
			public const int putBirthDay = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int putEmail = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
